server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
paypal:
  baseUrl: https://api-m.sandbox.paypal.com
  clientId: ${PAYPAL_ID}
  secret: ${PAYPAL_SECRET}